spring:
  datasource:
    url: jdbc:mysql://c88-mysql:3306/c88?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bEUCqBPijpcgoyVdj8hYjRTk
  redis:
    host: c88-redis
    port: 6379
    password: 78769184-fc2b-4ea3-a1bd-cc54be2fa5ea
    database: 0
  rabbitmq:
    host: c88-rabbitmq
    port: 5672
    username: default_user_Osv3MoxUtXtNvQmXeRN
    password: SGqGu_iWdeCQ2Liol0YjerADxrOASc3y
    listener:
      simple:
        acknowledge-mode: manual
  cloud:
    kubernetes:
      client:
        namespace: c88
  kafka:
    bootstrap-servers: 10.249.222.1:9092,10.249.222.2:9092,10.249.222.3:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

logging:
  level:
    org:
      springframework:
        security: debug
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: com.c88.admin.common.enums
#hystrix
feign:
  circuitbreaker:
    enabled: true


#storage configuration
cloud-storage:
  gcp:
    url: https://storage.googleapis.com/pre-comebet/
    project: pre-sports
    credentials-classpath: classpath:keys/k8s_pre/google-cloud-storage.json
    cdn: https://pre-testcdn.c88.biz/